export const TALENT_TYPES = [
  "A Cappella Group", "Accordion", "Acoustic Bass", "Acoustic Guitar",
  "African Drumming Group", "Arabic Band", "Armenian Specialist", "Audio Engineer",
  "Bagpipes", "Balalaika", "Ballroom Dancers", "Banjo", "Bass", "Bassoon",
  "Belly Dancer", "Bouzouki", "Brass Ensemble", "Brazilian Dance Troupe",
  "Caribbean Band", "Cello", "Children's Symphony", "Chinese Ensemble",
  "Clarinet", "Classical Ensemble", "Classical Guitar", "Conductor",
  "Country Western", "Cuban Specialist", "Dance Instructor", "Dixieland Band",
  "Drums", "Fiddle", "Flamenco Guitar", "Flamenco Dancer", "Flute",
  "French Horn", "Gospel Choir", "Greek Band", "Greek Specialist",
  "Guitar", "Harmonica", "Harp", "Hawaiian Specialist", "India Specialist",
  "Irish Specialist", "Israeli Specialist", "Italian Opera", "Italian Pop",
  "Japanese Ensemble", "Karaoke MC", "Keyboard", "Klezmer Ensemble",
  "Korean Ensemble", "Latin Band", "Latin Dance", "Latin Percussion",
  "Mandolin", "Marching Band", "Mariachi Ensemble", "MC",
  "Middle East Specialist", "Oboe", "Opera Singer", "Organ", "Oud",
  "Pedal Steel Guitar", "Percussion", "Persian Specialist", "Piano",
  "Rapper", "Reggae Band", "Rock Band", "Rock String Quartet",
  "Russian Specialist", "Salsa Dancers", "Saxophone", "Saxophone Alto",
  "Saxophone Baritone", "Saxophone Soprano", "Saxophone Tenor",
  "Sinatra Specialist", "Sitar", "Spanish Guitar", "Square Dance",
  "Steel Pans", "String Quartet", "Tabla", "Trombone", "Trumpet", "Tuba",
  "Turkish Specialist", "Ukulele", "Vibraphone", "Viola", "Violin",
  "Vocal Male", "Vocal Female", "Vocalist", "DJ", "Band", "Ensemble",
  "Dancer", "Musician", "Instrumentalist", "Performer",
  "Wedding Band", "Jazz Band", "Jazz Trio", "Jazz Quartet",
  "Soul Band", "R&B Singer", "Blues Band", "Swing Band",
  "Acoustic Duo", "String Duo", "Piano Trio", "Piano Bar",
  "Flute and Guitar", "Saxophone and Guitar", "Violin and Piano",
] as const;

export type TalentType = typeof TALENT_TYPES[number];
