export const TALENT_TYPES = [
  "A Cappella Group",
  "Accordion",
  "Acoustic Bass",
  "Acoustic Duo",
  "Acoustic Guitar",
  "Aida Trumpet",
  "African Drumming Group",
  "Arabic Band",
  "Armenian Specialist",
  "Audio Engineer",
  "Bagpipes",
  "Balalaika",
  "Ballroom Dancers",
  "Banjo",
  "Bass",
  "Bass / Guitar",
  "Bassoon",
  "Belly Dancer",
  "Blues Band",
  "Bouzouki",
  "Brass Ensemble",
  "Brazilian Dance Troupe",
  "Cajon",
  "Caribbean Band",
  "Cello",
  "Cello Electric",
  "Children's Symphony",
  "Chinese Ensemble",
  "Clarinet",
  "Classical Ensemble",
  "Classical Guitar",
  "Conductor",
  "Country Western",
  "Cuban Specialist",
  "Dance Instructor",
  "Dancer",
  "Dixieland Band",
  "DJ",
  "Drums",
  "Ensemble",
  "Fiddle",
  "Flamenco Dancer",
  "Flamenco Guitar",
  "Flugelhorn",
  "Flute",
  "Flute and Guitar",
  "French Horn",
  "French Specialist",
  "Gospel Choir",
  "Greek Band",
  "Greek Specialist",
  "Guitar",
  "Guitar / DJ",
  "Harmonica",
  "Harp",
  "Hawaiian Specialist",
  "India Specialist",
  "Instrumentalist",
  "Irish Specialist",
  "Israeli Specialist",
  "Italian Opera",
  "Italian Pop",
  "Italian Traditional",
  "Japanese Ensemble",
  "Jazz Band",
  "Jazz Quartet",
  "Jazz Trio",
  "Karaoke MC",
  "Keyboard",
  "Keyboard / Guitar",
  "KKaossilator",
  "Klezmer Ensemble",
  "Korean Ensemble",
  "Latin Band",
  "Latin Dance",
  "Latin Dance Contemporary",
  "Latin Dance Traditional",
  "Latin Perc / Vocal",
  "Latin Percussion",
  "Mandolin",
  "Marching Band",
  "Mariachi Ensemble",
  "MC",
  "Middle East Specialist",
  "Musician",
  "Oboe",
  "Opera Singer",
  "Organ",
  "Oud",
  "Pedal Steel Guitar",
  "Percussion",
  "Performer",
  "Persian Specialist",
  "Piano",
  "Piano / Guitar",
  "Piano Bar",
  "Piano Trio",
  "Polish Specialty",
  "R&B Singer",
  "Rapper",
  "Reggae Band",
  "Rock Band",
  "Rock String Quartet",
  "Russian Specialist",
  "Salsa Dancers",
  "Saxophone",
  "Saxophone Alto",
  "Saxophone Baritone",
  "Saxophone Soprano",
  "Saxophone Tenor",
  "Sax / Bass",
  "Sax / EWI",
  "Sax / Flute",
  "Set Band",
  "Shaku Hachi",
  "Sinatra Specialist",
  "Sitar",
  "Soul Band",
  "Spanish Classical Guitar",
  "Spanish Guitar",
  "Specialty Acts",
  "Square Dance",
  "Steel Pans",
  "String Duo",
  "String Quartet",
  "Strolling Minstrels",
  "Swing Band",
  "Tabla",
  "Trombone",
  "Trumpet",
  "Tuba",
  "Turkish Specialist",
  "Ukulele",
  "Vibraphone",
  "Viola",
  "Violin",
  "Violin and Piano",
  "Violin Ac. & Elec.",
  "Violin Electric",
  "Vocal Female",
  "Vocal Male",
  "Vocalist",
  "Voc R&B Female",
  "Voc R&B Male",
  "Wedding Band",
] as const;

export type TalentType = (typeof TALENT_TYPES)[number];
